name: Machine Learning Workflow CI

on:
  push:
    branches:
      - main
      - master

jobs:
  retrain-model:
    runs-on: ubuntu-latest

    steps:
    # 1. Mengunduh kode dari repositori GitHub ke runner
    - name: Checkout Repository
      uses: actions/checkout@v4

    # 2. Setup Python di lingkungan GitHub Actions
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'

    # 3. Memasang semua pustaka yang dibutuhkan proses training
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow==2.19.0 scikit-learn pandas numpy virtualenv

    # 4. Menjalankan MLflow Project dengan memaksa local backend store uri
    - name: Run MLflow Project
      run: |
        mlflow run MLProject --env-manager=local --backend-store-uri ./mlruns