name: Machine Learning Workflow CI

on:
  push:
    branches:
      - main
      - master

jobs:
  retrain-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow==2.19.0 scikit-learn pandas numpy virtualenv

    # Kita jalankan langsung skrip modelling menggunakan Python di root lingkungan kerja
    - name: Run MLflow Project
      run: |
        python MLProject/modelling.py